[build-system]
requires = ['flit_core>=3.2,<4']
build-backend = 'flit_core.buildapi'

[project]
name = 'MPh'
authors = [{name='John Hennig'}]
license = {file='license.txt'}
keywords = ['finite elements', 'computer simulation', 'physics',
            'multiphysics', 'Comsol']
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX :: Linux',
    'Operating System :: MacOS :: MacOS X',
    'Topic :: Scientific/Engineering :: Physics',
    'Intended Audience :: Science/Research',
    'Natural Language :: English',
    'License :: OSI Approved :: MIT License']
readme = 'pypi.md'
requires-python = '>=3.6'
dependencies = ['JPype1', 'NumPy']
dynamic = ['version', 'description']

[project.optional-dependencies]
doc = ['Sphinx', 'Furo', 'MyST-parser', 'CommonMark']
test = ['pyTest', 'pyTest-cov', 'coverage-badge', 'flake8']

[project.urls]
Documentation = 'https://mph.readthedocs.io'
Source = 'https://github.com/MPh-py/MPh'

[tool.flit.module]
name = 'mph'
