# Project information: PyPI and Pip

[project]
name = 'MPh'
authors = [{name='John Hennig'}]
license = {file='license.txt'}
keywords = ['Comsol', 'multiphysics', 'physics', 'finite elements',
            'computer simulation']
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX :: Linux',
    'Operating System :: MacOS :: MacOS X',
    'Topic :: Scientific/Engineering :: Physics',
    'Intended Audience :: Science/Research',
    'Natural Language :: English',
    'License :: OSI Approved :: MIT License']
readme = 'PyPI.md'
requires-python = '>=3.6'
dependencies = ['JPype1', 'NumPy']
dynamic = ['version', 'description']

[project.optional-dependencies]
docs = ['Sphinx', 'Furo', 'MyST-parser']
test = ['pyTest', 'pyTest-cov', 'Flake8', 'Flake8-pyproject']

[project.urls]
Documentation = 'https://mph.readthedocs.io'
Source = 'https://github.com/MPh-py/MPh'


# Wheel builder: Flit

[build-system]
requires = ['flit_core>=3.4,<4']
build-backend = 'flit_core.buildapi'

[tool.flit.module]
name = 'mph'


# Code linter: Flake8 (via pyproject-Flake8)

[tool.flake8]
exclude = [
    '.git', '__pycache__',
    'local', 'ignore', 'develop', 'dev',
]
ignore = [
    'E127',        # Continuation line over-indented for visual indent.
    'E128',        # Continuation line under-indented for visual indent.
    'E201',        # Whitespace after '('.
    'E202',        # Whitespace before ')'.
    'E221',        # Multiple spaces before operator.
    'E222',        # Multiple spaces after operator.
    'E226',        # Missing whitespace around arithmetic operator.
    'E231',        # Missing whitespace after ',', ';', or ':'.
    'E241',        # Multiple spaces after ','.
    'E251',        # Unexpected spaces around keyword / parameter equals.
    'E261',        # At least two spaces before inline comment.
    'E271',        # Multiple spaces after keyword.
    'E272',        # Multiple spaces before keyword.
    'E402',        # Module level import not at top of file.
    'W503',        # Line break occurred before a binary operator.
]
per-file-ignores = ['__init__.py:F401']


# Test runner: pyTest

[tool.pytest.ini_options]
addopts = '--verbose'
testpaths = ['tests']


# Code coverage: Coverage.py

[tool.coverage.run]
source = ['mph/']
omit = ['mph/discovery.py']
relative_files = true

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'def check_environment',
    'def location',
]
